### ISSUE TITLE
module functioning

### ISSUE THREAD

**Issue by AndrzejSzczepanik** [NKoonen/vatchecker#23]
I have been using the module for 2 years, there was a description somewhere before, I remember that the description explained that the VIES group should be created for which prices are displayed net - this setting is in the group configuration. The module probably assigned to this group based on the VAT ID and delivery address. Now I can see that it does not automatically assign to any group and will charge the customer in gross price and so he will sell / issue a prestashop invoice if I have not added the customer to the VIES group manually. Can someone explain exactly how this is supposed to work. Thank you in advance

**Comment by JoryHogeveen** [comment]
Hi @AndrzejSzczepanik 

You are describing an older version of this module. At that point it indeed assigned a user to a non-VAT group based on the VAT ID.
This however does not account for multiple addresses.

The new version of the module does vat validation based on the address, not the user. So an address is either VAT validated or not. If it is then VAT is disabled, otherwise it is enabled.
Group assignment (and groups in general) is something different entirely and it's (and should be) unrelated to VAT calculation.

**Comment by AndrzejSzczepanik** [comment]
OK, that's how I understood the intentions in the current version, but the tests show that if the user has VIES and the address is exported, he does not count and invoice net anyway, until he manually changes the group to VIES, then the net is invoiced, it would follow that I don't know about something else. Could you explain at what point in time this verification takes place, does it have any reflection in the customer's databases, etc., thank you beautifully

**Comment by AndrzejSzczepanik** [comment]
Thank you for your clarification, so I see that VAT checking is performed on demand, and it does not depends on customer group at all. Sounds nice, but please pay atention to this atached screens - it should't calucate a tax but it does calculate TAX. The same situation with the same user, when the user is assigned to  VIES group (what only lists product prices in net value) TAX is not included. What the explanation coud be? Prestshop 1.7.8.5 Vat checker today yesterdea reinstaled current version from this Giithub
![VatChecker bring us to pay without tax when user belogs to VIES group](https://user-images.githubusercontent.com/95178270/190482843-282695cc-537a-4971-88ae-fc9f4bb9fae5.jpg)
![Vies gropu configuration](https://user-images.githubusercontent.com/95178270/190482846-ff11eef4-9f55-4e8d-ab10-099e853b162e.jpg)
![Vat Checker config](https://user-images.githubusercontent.com/95178270/190482847-971e7ff6-ce08-4348-9aa9-d2e4ef67af23.jpg)
![VatChecker bring us to pay tax](https://user-images.githubusercontent.com/95178270/190482850-19254233-e8cc-4556-b68b-ab3f123a3c4b.jpg)

**Comment by AndrzejSzczepanik** [comment]
the last screen is situation when user does not belong to VIES group

**Comment by AndrzejSzczepanik** [comment]
Supporting information - the store is multi languges and multi currencies

**Comment by JoryHogeveen** [comment]
Hi @AndrzejSzczepanik 
Are you sure you are running the latest version? This plugin doesn't even check or validate a customer group so that is fully unrelated to any issue.
The mentioned group setting to show prices excluding taxes is also unrelated as this is only changing display, not the actual pricing.

Please make sure you re-install correctly.

**Comment by AndrzejSzczepanik** [comment]
You make me start thinking. I did uninstall, and install again, then I have checked in vatchecker table was created, because I see that it shoud be created when vatchecker is installed, so I get succes - table was created, and all start working exactly as it is discrbed !  Perfect module - sutis exactly the need. Thanky very mutch for puting some light how it works.

**Comment by AndrzejSzczepanik** [comment]
And this approach to the VAT issue ensures showing correct prices and bill calculation as well based on address and VAT id of delivery address - really perfect !!! you are clever guy!!
