### ISSUE TITLE
Not working for another invoice address

### ISSUE THREAD

**Issue by futurowebpl** [NKoonen/vatchecker#35]
The module does not work when the user provides a different invoice address than the delivery address - within one country it should work.

That is, if:

delivery address
Jan Kowalski
street 8
00-000 city
Romania

invoice address
Company Jan Kowalski
street 25
00-000 city
Romania
VAT EU: valid vat eu number

then the module does not provide the VAT rate because the user did not add the VAT number in the delivery address at all.

request for review.

**Comment by NKoonen** [comment]
Yes, this is actually on purpose. Because the intra-community supply law states that the delivery address should be abroad. So when we are validating a VAT number, we have to check the details for the delivery address and not the invoice address. Because even though a customer states that the invoice address has a valid VAT number, it could be completely different then the delivery address or VAT number.
